import type { Config } from "tailwindcss";

const config: Config = {
    content: [
        "./app/**/*.{js,ts,jsx,tsx,mdx}",
        "./components/**/*.{js,ts,jsx,tsx,mdx}",
        "./lib/**/*.{js,ts,jsx,tsx,mdx}",
    ],
    theme: {
        extend: {
            colors: {
                "surface-dim": "#d9dadb",
                "primary-fixed-dim": "#b2c5ff",
                "tertiary-fixed": "#ffdad8",
                "on-tertiary-fixed-variant": "#92001c",
                "surface": "#f8f9fa",
                "surface-container": "#edeeef",
                "on-surface": "#191c1d",
                "on-error": "#ffffff",
                "surface-tint": "#0056d2",
                "secondary": "#525f73",
                "on-background": "#191c1d",
                "tertiary-container": "#bb152c",
                "primary": "#0040a1",
                "surface-container-high": "#e7e8e9",
                "error": "#ba1a1a",
                "on-tertiary": "#ffffff",
                "surface-container-low": "#f3f4f5",
                "on-primary-fixed": "#001847",
                "error-container": "#ffdad6",
                "secondary-fixed": "#d6e3fb",
                "secondary-fixed-dim": "#bac7de",
                "outline": "#737785",
                "on-secondary-container": "#586579",
                "tertiary-fixed-dim": "#ffb3b1",
                "on-tertiary-fixed": "#410007",
                "secondary-container": "#d6e3fb",
                "on-error-container": "#93000a",
                "on-primary-fixed-variant": "#0040a1",
                "surface-bright": "#f8f9fa",
                "inverse-on-surface": "#f0f1f2",
                "on-tertiary-container": "#ffcdcb",
                "primary-fixed": "#dae2ff",
                "outline-variant": "#c3c6d6",
                "surface-container-lowest": "#ffffff",
                "on-secondary-fixed": "#011c2d",
                "primary-container": "#0056d2",
                "on-secondary-fixed-variant": "#3b485a",
                "on-secondary": "#ffffff",
                "background": "#f8f9fa",
                "tertiary": "#93001c",
                "surface-container-highest": "#e1e3e4",
                "on-primary": "#ffffff",
                "on-primary-container": "#ccd8ff",
                "inverse-surface": "#2e3132",
                "surface-variant": "#e1e3e4",
                "inverse-primary": "#b2c5ff",
                "on-surface-variant": "#424654"
            },
            fontFamily: {
                sans: ['var(--font-outfit)', 'ui-sans-serif', 'system-ui', 'sans-serif'],
                headline: ['var(--font-outfit)', 'sans-serif'],
                body: ['var(--font-outfit)', 'sans-serif'],
                label: ['var(--font-outfit)', 'sans-serif'],
            },
        },
    },
    plugins: [],
};

export default config;
